### ISSUE TITLE
Floating point exception, DS Assingment 2, Q2B

### ISSUE THREAD

**Issue by ronalddas** [MIT-CSE-2019/SEM3#8]
Basically need to use long long or double to get rid of the error.[https://github.com/MIT-CSE-2019/SEM3/blob/master/Assignments/DS/Assignment2/2B.c](url)

**Comment by udayakumar97** [comment]
The problem was in the return statement of the function where integer division was happening. Moreover there was a problem in the logic used. Though it gives correct output it was both memory and space inefficient. The logic has been improved.

**Comment by ronalddas** [comment]
Okay, thanks, its working now.
